name: Build website

on: [push]

jobs:
  hugo:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # https://github.com/actions/checkout#Checkout-submodules
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Build
      run: |
        docker run --rm -i \
          -v $(pwd):/src \
          -e HUGO_DESTINATION=public \
          klakegg/hugo:ext-alpine
